proj_SIGApoio/app/urls.py
from .views import efetuarChamado, home, getLocais, cadastroRecurso, cad_local, listar_local, success_page, cadastroTipoRecurso, listarRecursos, cadastroReservaSemanal, tipoReserva, cadastroReservaDia, cadastroReservaMensal, reserva_recurso, listarReservas, reservaDetails, filtrarReservas, filtrosReserva, getLocaisDia, listar_emprestimos
from django.urls import path

urlpatterns = [
    path('', home, name = 'home'),
    path('recurso/cadastro', cadastroRecurso, name='cadastro-recurso'),
    path('recurso/cadastro-tipo-recurso', cadastroTipoRecurso, name='cadastro-tipo-recurso'),
    path('recurso/listar', listarRecursos, name='listar-recurso'),
    path('chamado', efetuarChamado, name='efetuar-chamado'),
    path('reservas', listarReservas, name='listar-reservas'),
    path('filtros_reserva', filtrosReserva, name='filtros-reserva'),
    path('lista_filtrada', filtrarReservas, name='filtrar-reservas'),
    path('reserva_details', reservaDetails, name = "reservaDetails"),
    path('cadastro_recurso',cadastroRecurso, name= "cad_recurso"),
    path('cad_local/', cad_local, name = "cad_local"),
    path('success_page/', success_page, name = "success_page"),
    path('reserva_recurso/', reserva_recurso, name='reserva_recurso'),
    path('emprestimos/', listar_emprestimos, name='listar_emprestimos'),
    path('local/listar/', listar_local, name='listar_local'),
    path('local/cad_local', cad_local, name = "cad_local"),
    path('reserva/cadastro/semanal', cadastroReservaSemanal, name = "cad_reserva_semanal"),
    path('reserva/cadastro/dia', cadastroReservaDia, name = "cad_reserva_dia"),
    path('reserva/cadastro/', tipoReserva, name = "cad_reserva"),
    path('get_locais/', getLocais, name = "getLocais"),
    path('get_locais_dia/', getLocaisDia, name = "getLocaisDia")
]

proj_SIGApoio/core/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('get_locais/', views.getLocais, name = "getLocais"),
    path('success_page/', views.success_page, name = "success_page")
]

proj_SIGApoio/proj_SIGApoio/urls.py
from django.contrib import admin
from django.urls import path, include
from app_SIGApoio import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.home,name = "home"),
    path('cadastro_recurso',views.cadastroRecurso, name= "cad_recurso"),
    path('cad_local/',views.cad_local, name = "cad_local"),
    path('success_page/', views.success_page, name = "success_page"),
    path('cad_reserva/', views.cadastroReserva, name = "cad_reserva"),
    path('get_locais/', views.getLocais, name = "getLocais"),
    path('admin/', admin.site.urls),
    path('', include('app_SIGApoio.urls'))
    ]

proj_SIGApoio/app/forms.py
from django import forms
from django.db import connection
from .models import Recurso, TipoRecurso, Local, TipoLocal, Usuario, ReservaSemanal, ReservaDiaUnico, Chamado


BLOCOS_CHOICES = [('A', 'Bloco A'), ('B', 'Bloco B'), ('C', 'Bloco C'), ('D', 'Bloco D'), ('Aud', 'Auditórios'), ('Lab', 'Laboratórios')]

def get_usuario_choices():
    try:
        if 'app_usuario' in connection.introspection.table_names():
            print('achou usuário')
            return [(usuario.matricula, usuario.nome) for usuario in Usuario.objects.all()]
        else:
            return []
            print('nao achou usuário')
        
    except Exception as e:
        print('deu erro')
        return []
    
class TipoRecursoForm(forms.Form, forms.ModelForm):
    tipo = forms.CharField(
        label = 'Tipo',
        widget = forms.TextInput(attrs={'class':'form-control'}) 
    )
    
    class Meta:
        model = TipoRecurso
        fields = ['tipo']

class RecursoForm(forms.Form, forms.ModelForm):
    codigo = forms.CharField(
        label='Código',
        widget=forms.TextInput(attrs={'class':'form-control'})
    )

    tipo = forms.ModelChoiceField(
        queryset=TipoRecurso.objects.all(),
        label='Tipo',
        widget=forms.Select(attrs={'class':'form-control', 'style':'color: black'})
    )

    status = forms.ChoiceField(
        choices=Recurso.STATUS_CHOICE,
        widget=forms.Select(attrs={'class':'form-control', 'style':'color: black'})
    )

    funcionando = forms.ChoiceField(
        choices=Recurso.FUNCIONANDO_CHOICE,
        widget=forms.Select(attrs={'class':'form-control', 'style':'color: black'})
    )

    class Meta:
        model = Recurso
        fields = ['codigo','tipo', 'status', 'funcionando']  

class ChamadoForm(forms.Form, forms.ModelForm):
    chamado = forms.CharField(
        label='Chamado',
        widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Escreva sua mensagem aqui!'})
    )

    reserva = forms.ModelChoiceField(
        queryset= ReservaSemanal.objects.all(),
        label='Reserva',
        widget=forms.Select(
            attrs={
                'class': 'form-select gray-back blue-text me-4'
            }
        )
    )

    class Meta:
        model = Chamado
        fields = ['chamado', 'reserva']

class LocalForm(forms.ModelForm):
    tipo = forms.ModelChoiceField(
        queryset=TipoLocal.objects.all(),
        label='Tipo de Local',
        widget=forms.Select(attrs={'class': 'form-control', 'style': 'color: black'})
    )

    class Meta:
        model= Local
        fields= "__all__"
        
class ReservaForm(forms.ModelForm, forms.Form):
    descricao = forms.CharField(
        label='Descrição',
        widget=forms.TextInput(
            attrs={'class': 'form-control blue-text gray-back me-4'}
        )
    )
    
    horarios = forms.MultipleChoiceField(
        label="Horários",
        choices=[
            ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'), ('M6', 'M6'),
            ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6'),
            ('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4')
        ],
        widget=forms.SelectMultiple(
            attrs={
                'class': 'form-select gray-back blue-text me-4'
            }
        )
    )
    
    dias = forms.MultipleChoiceField(
        label='Dia(s)',
        choices=[
            ('2', 'Segunda'),
            ('3', 'Terça'),
            ('4', 'Quarta'),
            ('5', 'Quinta'),
            ('6', 'Sexta'),
        ],
        widget=forms.SelectMultiple(
            attrs={
                'class': 'form-select gray-back blue-text me-4'
            }
        )
    )
    
    qtd_pessoas = forms.IntegerField(
        max_value=250,
        initial=0,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control gray-back blue-text me-4'
            },
        )
    )
    
    bloco = forms.ChoiceField(
        choices=BLOCOS_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-select gray-back blue-text me-4'
            }
        )
    )
    
    matSolicitante = forms.ChoiceField(
        label="Solicitante",
        choices=get_usuario_choices(),
        widget=forms.Select(
            attrs={
                'class': 'form-select gray-back blue-text me-4'
            }
        )
    )    
    
    local = forms.ChoiceField(
        label="Local",
        widget=forms.Select(
            attrs={
                'class': 'form-select gray-back blue-text me-4'
            }
        )
    )

    class Meta:
        model = ReservaSemanal
        fields = ['horarios', 'dias', 'qtd_pessoas', 'matSolicitante', 'local']
        
    def __init__(self, *args, **kwargs):
        super(ReservaForm, self).__init__(*args, **kwargs)
        self.fields['local'].queryset = Local.objects.none()

        if 'horarios' and 'dias' in self.data:
            try:
                self.fields['local'].queryset = \
                    Local.objects.all().order_by('nome')
                print(self.fields['local'].queryset)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Horarios queryset
        elif self.instance.pk:
            self.fields['local'].queryset = Local.objects.none()

class ReservaDiaForm(forms.ModelForm, forms.Form):
    descricao = forms.CharField(
        label='Descrição',
        widget=forms.TextInput(
            attrs={'class': 'form-control blue-text gray-back me-4'}
        )
    )
    
    local = forms.ChoiceField(
        label='Local',
        widget=forms.Select(
            attrs={'class': 'form-select blue-text gray-back me-4'}
        )
    )
    
    diaHoraInicio = forms.DateTimeField(
        label="Início da reserva",
        widget=forms.DateTimeInput(
            attrs={'class': 'form-control blue-text gray-back me-4', 'type': 'datetime-local'}
        )
    )
    
    diaHoraFim = forms.DateTimeField(
        label="Fim da reserva",
        widget=forms.DateTimeInput(
            attrs={'class': 'form-control blue-text gray-back me-4', 'type': 'datetime-local'}
        )
    )
    
    repeticao = forms.ChoiceField(
        choices=[('unico', 'Única'), ('semana', 'Semanal'), ('mes', 'Mensal')],
        widget=forms.Select(
            attrs={
                'class': 'form-select gray-back blue-text me-4'
            },
        )
    )
    
    qtd_pessoas = forms.IntegerField(
        max_value=250,
        initial=0,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control gray-back blue-text me-4'
            },
        )
    )
    
    bloco = forms.ChoiceField(
        choices=BLOCOS_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-select gray-back blue-text me-4'
            }
        )
    )
    
    matSolicitante = forms.ChoiceField(
        label='Solicitante',
        choices=get_usuario_choices(),
        widget=forms.Select(
            attrs={'class': 'form-select blue-text gray-back me-4'}
        )
    )
    
    class Meta:
        model = ReservaDiaUnico
        fields = ['descricao', 'diaHoraInicio', 'diaHoraFim', 'local', 'matSolicitante']

proj_SIGApoio/app/templates/reserva/cadastroReserva.html
{% extends "base.html" %}

{% block content %}

<style>
    #ReservaFormDom {
        max-width: 70%;
    }
</style>

<h1 class="text-center mt-4 pt-4 blue-text">Cadastro de Reserva</h1>
<form action="{% url 'cad_reserva_semanal' %}" method="POST" id="ReservaFormDom" locais_url="{% url 'getLocais' %}" class="container text-start">
    {% csrf_token %}
    <hr class="ms-4 me-4 blue-text">
    {% if message %}
    <h5 class="{% if error %}text-danger{% else %}text-success{% endif %} text-center">{{ message }}</h5>
    {% endif %}
    <div class="px-4 pb-4">
        <h5>Descrição</h5>
        {{ form.descricao }}
    </div>
    <div class="d-flex justify-content-between gap-4 px-4">
        <div class="flex-fill">
            <h5>Dias</h5>
            {{ form.dias }}
        </div>
        <div class="flex-fill">
            <h5>Horários</h5>
            {{ form.horarios }}
        </div>
    </div>
    <div class="d-flex justify-content-between gap-4 p-4">
        <div class="flex-fill">
            <h5>Nº de pessoas</h5>
            {{ form.qtd_pessoas }}
        </div>
        <div class="flex-fill">
            <h5>Bloco</h5>
            {{ form.bloco }}
        </div>
    </div>
    <div class="px-4 pb-4">
        <h5>Solicitante da reserva</h5>
        {{ form.matSolicitante }}
    </div>
    <!-- <div class="px-4 pb-4">
        <h5>Matrícula do Responsável</h5>
        {{ form.matResponsavel }}
    </div> -->
    <div class="px-4 pb-4">
        <h5>Local</h5>
        {{ form.local }}
    </div>
    <div class="text-end me-2 pe-4 pb-4 mb-4">
        <button class="btn blue-btn btn-primary" type="submit">Enviar</button>
    </div>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script type="text/javascript">
    onChangeHorarios = () => {
        const url = $('#ReservaFormDom').attr('locais_url');
        horarios = $("#id_horarios").val();
        dias = $("#id_dias").val();
        pessoas = $("#id_qtd_pessoas").val();
        bloco = $("#id_bloco").val();

        $.ajax({
            type: 'POST',
            url: url,
            data: JSON.stringify({ 'horarios': horarios, 'dias': dias, 'pessoas': pessoas, 'bloco': bloco}),
            success: (data) => {
                if(data.length == 0){
                    data = '<option disabled selected>Nenhum local disponível</option>'
                }
                $('#id_local').html(data);
            }
        })
    }

    $("#id_horarios").change(onChangeHorarios)
    $("#id_dias").change(onChangeHorarios)
    $("#id_qtd_pessoas").change(onChangeHorarios)
    $("#id_bloco").change(onChangeHorarios)


</script>

{% endblock content %}

proj_SIGApoio/app/templates/reserva/cadastroReservaDia.html
{% extends "base.html" %}

{% block content %}

<style>
    #ReservaFormDom {
        max-width: 70%;
    }
</style>

<h1 class="text-center mt-4 pt-4 blue-text">Cadastro de Reserva</h1>
<form action="{% url 'cad_reserva_dia' %}" method="POST" id="ReservaFormDom" locais_url="{% url 'getLocaisDia' %}" class="container text-start">
    {% csrf_token %}
    <hr class="ms-md-4 me-md-4 blue-text">
    {% if message %}
    <h5 class="{% if error %}text-danger{% else %}text-success{% endif %} text-center">{{ message }}</h5>
    {% endif %}
    <div class="px-md-4 pb-4">
        <h5>Descrição</h5>
        {{ form.descricao }}
    </div>
    <div class="d-flex justify-content-between gap-4 px-md-4 mb-4 flex-column flex-md-row">
        <div class="flex-fill">
            <h5>Início</h5>
            {{ form.diaHoraInicio }}
        </div>
        <div class="flex-fill">
            <h5>Fim da reserva</h5>
            {{ form.diaHoraFim }}
        </div>
        <div class="flex-fill">
            <h5>Repetição</h5>
            {{ form.repeticao }}
        </div>
    </div>
    <div class="d-flex justify-content-between flex-column flex-md-row gap-4 mb-4 p-md-4">
        <div class="flex-fill">
            <h5>Nº de pessoas</h5>
            {{ form.qtd_pessoas }}
        </div>
        <div class="flex-fill">
            <h5>Bloco</h5>
            {{ form.bloco }}
        </div>
    </div>
    <div class="px-md-4 pb-4">
        <h5>Local</h5>
        {{ form.local }}
    </div>
    <div class="px-md-4 pb-4">
        <h5>Solicitante da reserva</h5>
        {{ form.matSolicitante }}
    </div>
    <!-- <div class="px-4 pb-4">
        <h5>Matrícula do Responsável</h5>
        {{ form.matResponsavel }}
    </div> -->
    <div class="text-end me-2 pe-4 pb-4 mb-4">
        <button class="btn blue-btn btn-primary" type="submit">Enviar</button>
    </div>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script type="text/javascript">
    onChangeHorarios = () => {
        const url = $('#ReservaFormDom').attr('locais_url');
        horarios = $("#id_horarios").val();
        dia = $("#id_diaHoraInicio").val();
        diaFim = $("#id_diaHoraFim").val();
        pessoas = $("#id_qtd_pessoas").val();
        bloco = $("#id_bloco").val();

        $.ajax({
            type: 'POST',
            url: url,
            data: JSON.stringify({ 'horarios': horarios, 'diaInicio': dia, 'diaFim': diaFim, 'pessoas': pessoas, 'bloco': bloco}),
            success: (data) => {
                if(data.length == 0){
                    data = '<option disabled selected>Nenhum local disponível</option>'
                }
                $('#id_local').html(data);
            }
        })
    }

    $("#id_diaHoraInicio").change(onChangeHorarios)
    $("#id_diaHoraFim").change(onChangeHorarios)
    $("#id_qtd_pessoas").change(onChangeHorarios)
    $("#id_bloco").change(onChangeHorarios)


</script>

{% endblock content %}

proj_SIGApoio/app/templates/reserva/efetuar_chamado.html
{% extends "base.html" %}

{% block content %}

    <style>
        h1{
            color: #0800B5;
            text-align: center;
        }

        button{
            background-color: #0800B5;
            color: white;
        }

        .botao{
            display: flex;
            justify-content: center;
        }

        .line1{
            border:1px solid #0800b5;
        }

        select, input{
            border-color: #0800b5;
            border-radius: 5px;
        }

    </style>

    <title>Efetuar Chamado</title>

    <div class="container-fluid">
        <form action="{% url 'efetuar-chamado' %}" method="post" class="container-fluid" style="max-width: 40em;">
            <h1>Efetuar Chamado</h1>
            <div id='line1' class='line1'></div> </br>
            {% csrf_token %}
            {{ form.as_p }}
            <div id='line1' class='line1'></div></br>
            <div class="botao">
                <button name="submit" class="buttons">Enviar</button>
            </div>
        </form>
    </div>
    
{% endblock content %}

proj_SIGApoio/app/templates/reserva/filtros_reserva.html
{% load func_utils %}
{{ filtro|criar_filtro }}

<script>
    filtrar = () => {
        var radio = $('input[name="flexRadioDefault"]:checked').val();
        const url = "{% url 'filtrar-reservas' %}"
 
        var tipo_reserva = "default";
        var local_reserva = "default";
        var resp_reserva = "default";

        if (radio == 2){
            tipo_reserva = $("#filtro_tipo_reserva").val();
        }else if (radio == 3){
            local_reserva = $("#filtro_local_reserva").val();
        }else if (radio == 4){
            resp_reserva = $("#filtro_resp_reserva").val();
        }
        
        


        $.ajax({
            url: url,
            data: {'filtro_tipo': tipo_reserva,
                   'filtro_local': local_reserva,
                   'filtro_resp': resp_reserva},
            success: function(response) {
                $("#tbody").html(response);
            }
        });

    };


    $("#filtro_tipo_reserva").change(filtrar);
    $("#filtro_local_reserva").change(filtrar);
    $("#filtro_resp_reserva").change(filtrar);
</script>

proj_SIGApoio/app/templates/reserva/lista_filtrada.html
{% load func_utils %}
{% for reserva in reservas %}
    {% if filtro_local == 'default' or filtro_local == reserva.local.pk|to_str %}
        {% if filtro_tipo == reserva|get_tipo_reserva or filtro_tipo == 'default' %}
            {{reserva|linha_tabela}}
        {% endif %}
    {% endif %}    
{% endfor %}

<script>
    $(".reserva").on('click',function(event) {
        const url = "{% url 'reservaDetails' %}";
        var what_reserva = $(this).attr('idReserva');
        var reserva_tipo = $(this).attr('tipoR');

        console.log(what_reserva)
        //console.log(url)
        $.ajax({
                url: url,
                data: {'reserva_pk': what_reserva, 'reserva_tipo': reserva_tipo},
                success: function(response) {
                    $('#detalhes').html(response);
                }
            });
        event.preventDefault();
    });
</script>

proj_SIGApoio/app/templates/reserva/listar_reservas.html
{% extends "base.html" %}

{% block content %}

    <style>
        h1{
            color: #0800B5;
            text-align: center;
        }

        button{
            background-color: #0800B5;
            color: white;
        }

        .botao{
            display: flex;
            justify-content: center;
        }

        .line1{
            border:1px solid #0800b5;
        }

        select, input{
            border-color: #0800b5;
            border-radius: 5px;
        }

        #detalhes{
            padding: 1em 5em;
        }

        .table{
            text-align: center;
        }

        .radios{
            display: flex;
            align-items: center;
            justify-content: space-evenly;
        }


    </style>

    <title>Listar Reservas</title>

    <div class="container-fluid">
        <h1>Listagem de reservas</h1>
        <div id='line1' class='line1'></div></br>

        <div>
            <div class="radios" id="radios">
                <h4>Filtrar por:</h4>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioTodos1" value="1">
                    <label class="form-check-label" for="flexRadioTodos1">Todos</label>
                </div>
                
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioTipo2" value="2">
                    <label class="form-check-label" for="flexRadioTipo2">Tipo</label>
                </div>
                
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioLocal3" value="3">
                    <label class="form-check-label" for="flexRadioLocal3">Local</label>
                </div>

                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioResp4" value="4">
                    <label class="form-check-label" for="flexRadioResp4">Responsavel</label>
                </div>
            </div>

            <div id='line1' class='line1'></div></br>

            <div id="filtros"></div>

            <div id="detalhes"></div>
            
            <div id='line1' class='line1'></div></br>
            
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Código</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Local</th>
                    <th scope="col">Responsável</th>
                </tr>
            </thead>
            <tbody id="tbody">
                
            </tbody>
        </table>

        <div id='line1' class='line1'></div></br>

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <script type="text/javascript">

        $('.radios').change(()=>{
            var radio = $('input[name="flexRadioDefault"]:checked').val();
            console.log(radio)


                $.ajax({
                    url: "{% url 'filtrar-reservas' %}",
                    data: {'filtro_tipo': "default",
                        'filtro_local': "default",
                        'filtro_resp': "default"},
                    success: function(response) {
                        $("#tbody").html(response);
                    }
                });
                $.ajax({
                    url: "{% url 'filtros-reserva' %}",
                    data: {'filtro': radio},
                    success: function(response) {
                        $('#filtros').html(response);
                    }
                });
            
            
        });

    
        //função de exibir os detalhes quando clicar na reserva
        $(".reserva").on('click',function(event) {
            const url = $(this).attr('url');
            var what_reserva = $(this).attr('idReserva');
            var reserva_tipo = $(this).attr('tipoR');

            $.ajax({
                    url: url,
                    data: {'reserva_pk': what_reserva, 'reserva_tipo': reserva_tipo},
                    success: function(response) {
                        $('#detalhes').html(response);
                    }
                });
            event.preventDefault();
        });




    </script>
    
{% endblock content %}

proj_SIGApoio/app/templates/reserva/local_option.html
{% for local in locais %}
<option value="{{ local.pk }}">{{ local }}</option>
{% endfor %}

proj_SIGApoio/app/templates/reserva/reserva_details.html
{% load func_utils %}

{{ reserva|detalhar}}

proj_SIGApoio/app/templates/reserva/tipoReserva.html
{% extends "base.html" %}

{% block content %}

<h1 class="text-center mt-4 pt-4">Cadastro de Reserva</h1>
<div class="container px-4">
    <hr class="blue-text" />
    <h4 class="text-center p-4">Selecione o tipo de reserva:</h4>
    <div class="container d-flex justify-content-evenly flex-column flex-sm-row gap-3">
        <a class="btn btn-primary btn-lg" href="{% url "cad_reserva_dia" %}">Personalizada</a>
        <a class="btn btn-primary btn-lg" href="{% url "cad_reserva_semanal" %}">Semanal</a>
    </div>
</div>

{% endblock content %}